/**
 * ArogyaNetra AI - Results Screen
 * Comprehensive scan results dashboard with health score, disease cards, vitals,
 * ARE explanations, diet recommendations, and downloadable reports
 */

import React, { useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Animated,
  Share,
  Alert,
} from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { GlassCard, AnimatedButton, RiskGauge, VitalPill } from '../components/common';
import { DiseaseCard } from '../components/results/DiseaseCard';
import { Colors, Typography, Spacing, BorderRadius } from '../theme';
import { useAppStore } from '../store/useAppStore';
import type { HomeStackParamList } from '../models/types';

type NavProp = NativeStackNavigationProp<HomeStackParamList, 'Results'>;

export const ResultsScreen: React.FC = () => {
  const navigation = useNavigation<NavProp>();
  // useRoute with any — this screen is used in both HomeStack (Results)
  // and ProfileStack (ResultDetail), both passing { scanId: string }
  const route = useRoute<any>();
  const { getStoredScan, currentScan, user } = useAppStore();

  const scan = getStoredScan(route.params?.scanId) || currentScan;
  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 600,
      useNativeDriver: true,
    }).start();
  }, []);

  if (!scan) {
    return (
      <View style={styles.container}>
        <Text style={styles.error}>Scan not found</Text>
      </View>
    );
  }

  const { diseases, vitals, areExplanation, overallHealthScore } = scan;
  const scoreColor = overallHealthScore >= 70 ? Colors.success
    : overallHealthScore >= 50 ? Colors.warning
    : Colors.danger;

  const handleShareReport = async () => {
    try {
      const date = new Date(scan.timestamp).toLocaleDateString('en-IN', {
        day: 'numeric', month: 'long', year: 'numeric',
      });

      const report = `
🏥 AAROGYANETRA AI - Health Report
📅 ${date} | 📊 Score: ${overallHealthScore}/100

━━ VITALS ━━
❤️ HR: ${vitals.heartRate} BPM | SpO2: ${vitals.spo2Proxy}%
🩺 BP: ${vitals.bloodPressureSystolic}/${vitals.bloodPressureDiastolic} mmHg

━━ RISK ANALYSIS ━━
❤️ Hypertension: ${diseases.hypertension.category} (${Math.round(diseases.hypertension.riskScore * 100)}%)
🩸 Diabetes: ${diseases.diabetes.category} (${Math.round(diseases.diabetes.riskScore * 100)}%)
👁️ Anemia: ${diseases.anemia.category} (${Math.round(diseases.anemia.riskScore * 100)}%)

${areExplanation.summary}

💡 ${areExplanation.counterfactual}

⚠️ Screening tool only — not a diagnosis.
Generated by AarogyaNetra AI
`.trim();

      await Share.share({
        message: report,
        title: 'AarogyaNetra Health Report',
      });
    } catch (err) {
      Alert.alert('Error', 'Failed to share report.');
    }
  };

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      <Animated.View style={{ opacity: fadeAnim }}>
        {/* Normal Camera Badge */}
        <View style={styles.labBadge}>
          <Text style={styles.labBadgeText}>📷 Scanned with Normal Camera</Text>
        </View>

        {/* Lab Data Badge */}
        {scan.usedLabData && (
          <View style={styles.labBadge}>
            <Text style={styles.labBadgeText}>
              ✅ Lab report data used — Higher accuracy
            </Text>
          </View>
        )}



        {/* Health Score Header */}
        <View style={styles.scoreSection}>
          <RiskGauge
            score={overallHealthScore}
            size={160}
            strokeWidth={14}
            label="Health Score"
            color={scoreColor}
          />
          <Text style={styles.scoreInterpretation}>
            {overallHealthScore >= 80 ? '🌟 Excellent Health Profile' :
             overallHealthScore >= 65 ? '👍 Good — Minor attention needed' :
             overallHealthScore >= 45 ? '⚠️ Moderate — Consult a physician' :
             '🚨 Elevated Risk — Seek medical advice'}
          </Text>
        </View>

        {/* Disease Risk Cards */}
        <Text style={styles.sectionTitle}>Disease Analysis</Text>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.diseaseScroll}
        >
          <DiseaseCard
            name="Hypertension"
            riskLevel={diseases.hypertension.riskLevel}
            riskScore={diseases.hypertension.riskScore}
            confidence={diseases.hypertension.confidence}
            keyMetric={{
              label: 'BP',
              value: `${diseases.hypertension.systolicEstimate}/${diseases.hypertension.diastolicEstimate}`,
              unit: 'mmHg',
            }}
            category={diseases.hypertension.category}
            icon="❤️"
          />
          <DiseaseCard
            name="Diabetes"
            riskLevel={diseases.diabetes.riskLevel}
            riskScore={diseases.diabetes.riskScore}
            confidence={diseases.diabetes.confidence}
            keyMetric={{
              label: 'HbA1c',
              value: diseases.diabetes.hba1cProxy,
              unit: '%',
            }}
            category={diseases.diabetes.category}
            icon="🩸"
          />
          <DiseaseCard
            name="Anemia"
            riskLevel={diseases.anemia.riskLevel}
            riskScore={diseases.anemia.riskScore}
            confidence={diseases.anemia.confidence}
            keyMetric={{
              label: 'Hb',
              value: diseases.anemia.hemoglobinEstimate,
              unit: 'g/dL',
            }}
            category={diseases.anemia.category}
            icon="👁️"
          />
        </ScrollView>

        {/* Vitals Strip */}
        <Text style={styles.sectionTitle}>Vital Signs</Text>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.vitalsScroll}
        >
          <VitalPill
            label="Heart Rate"
            value={vitals.heartRate}
            unit="BPM"
            color={Colors.hypertension}
          />
          <VitalPill
            label="SpO2"
            value={vitals.spo2Proxy}
            unit="%"
            color={Colors.secondary}
          />
          <VitalPill
            label="Resp Rate"
            value={vitals.respiratoryRate}
            unit="/min"
            color={Colors.primary}
          />
          <VitalPill
            label="Systolic"
            value={vitals.bloodPressureSystolic}
            unit="mmHg"
            color={Colors.accent}
          />
          <VitalPill
            label="Diastolic"
            value={vitals.bloodPressureDiastolic}
            unit="mmHg"
            color={Colors.anemia}
          />
        </ScrollView>

        {/* ARE Explanation */}
        <Text style={styles.sectionTitle}>🧠 AI Explanation</Text>
        <GlassCard variant="accent" style={styles.areCard}>
          <Text style={styles.areSummary}>{areExplanation.summary}</Text>

          {areExplanation.details.map((detail, idx) => (
            <Text key={idx} style={styles.areDetail}>
              • {detail}
            </Text>
          ))}

          {/* Feature Importance */}
          {areExplanation.featureImportance.length > 0 && (
            <View style={styles.featureSection}>
              <Text style={styles.featureTitle}>Key Contributing Factors</Text>
              {areExplanation.featureImportance.map((f, idx) => (
                <View key={idx} style={styles.featureRow}>
                  <View style={styles.featureBar}>
                    <View
                      style={[
                        styles.featureBarFill,
                        { width: `${f.contribution * 100}%` },
                      ]}
                    />
                  </View>
                  <Text style={styles.featureLabel}>
                    {f.feature} ({Math.round(f.contribution * 100)}%)
                  </Text>
                </View>
              ))}
            </View>
          )}

          {/* Counterfactual */}
          <GlassCard style={styles.counterfactualCard}>
            <Text style={styles.counterfactualTitle}>💡 What could help?</Text>
            <Text style={styles.counterfactualText}>
              {areExplanation.counterfactual}
            </Text>
          </GlassCard>
        </GlassCard>

        {/* XAI: Contribution Weights */}
        <Text style={styles.sectionTitle}>⚖️ Contribution Weights</Text>
        <GlassCard style={styles.xaiCard}>
          {[
            { label: 'Sleep & Lifestyle Input', weight: 35, color: Colors.primary },
            { label: 'Symptom Questionnaire', weight: 25, color: Colors.secondary },
            { label: 'Face Scan (rPPG)', weight: 20, color: Colors.warning },
            { label: 'Thermal / Camera Data', weight: 20, color: Colors.accent },
          ].map((item, idx) => (
            <View key={idx} style={styles.weightRow}>
              <View style={styles.weightLabelRow}>
                <Text style={styles.weightLabel}>{item.label}</Text>
                <Text style={[styles.weightPercent, { color: item.color }]}>{item.weight}%</Text>
              </View>
              <View style={styles.weightTrack}>
                <View style={[styles.weightFill, { width: `${item.weight}%`, backgroundColor: item.color }]} />
              </View>
            </View>
          ))}
        </GlassCard>

        {/* XAI: AI Reasoning */}
        <Text style={styles.sectionTitle}>🧠 AI Reasoning</Text>
        <GlassCard style={styles.xaiCard}>
          <Text style={styles.reasoningText}>
            {`Your overall health score of ${scan.overallHealthScore}/100 was determined by combining your symptom responses with facial scan analysis. ${
              scan.diseases.hypertension.riskScore > 0.5
                ? 'Elevated hypertension risk was detected mainly due to cardiovascular indicators from your pulse analysis and reported symptoms.'
                : scan.diseases.diabetes.riskScore > 0.5
                ? 'Moderate diabetes risk was flagged based on HRV depression patterns and your lifestyle inputs.'
                : scan.diseases.anemia.riskScore > 0.5
                ? 'Anemia indicators were detected through conjunctival pallor analysis and reported fatigue symptoms.'
                : 'No major risk flags were identified. Your vitals and scan indicators are within healthy ranges.'
            }`}
          </Text>
        </GlassCard>

        {/* Transparency Layer */}
        <Text style={styles.sectionTitle}>📜 Transparency</Text>
        <GlassCard style={styles.xaiCard}>
          <View style={styles.transRow}>
            <Text style={styles.transLabel}>Model</Text>
            <Text style={styles.transValue}>Multi-signal Fusion (rPPG + Symptom + Profile)</Text>
          </View>
          <View style={styles.transRow}>
            <Text style={styles.transLabel}>Data Sources</Text>
            <Text style={styles.transValue}>User inputs + Camera scan + rPPG analysis</Text>
          </View>
          <View style={styles.transRow}>
            <Text style={styles.transLabel}>Confidence</Text>
            <Text style={styles.transValue}>{scan.usedLabData ? 'High (lab-calibrated)' : 'Moderate (simulation-based)'}</Text>
          </View>
          <Text style={styles.transDisclaimer}>
            ⚠️ This is a screening tool only. It is NOT a medical diagnosis. Always consult a qualified healthcare professional.
          </Text>
        </GlassCard>

        {/* Action Buttons */}
        <View style={styles.actions}>
          <AnimatedButton
            title="🍽️ View Diet Recommendations"
            onPress={() => {
              try { navigation.navigate('Diet', { scanId: scan.scanId }); } catch (_) {
                Alert.alert('Diet Plan', 'Open this from the Home tab to view Diet Plan.');
              }
            }}
            variant="primary"
            fullWidth
            style={styles.actionBtn}
          />
          <AnimatedButton
            title="📤 Share / Download Report"
            onPress={handleShareReport}
            variant="primary"
            fullWidth
            style={{ ...styles.actionBtn, backgroundColor: Colors.secondary }}
          />
          <AnimatedButton
            title="📊 Risk Forecast (DREM)"
            onPress={() => {
              try { navigation.navigate('DREM', { scanId: scan.scanId }); } catch (_) {
                Alert.alert('DREM', 'Open this from the Home tab to view Risk Forecast.');
              }
            }}
            variant="outline"
            fullWidth
            style={styles.actionBtn}
          />
          <AnimatedButton
            title="🔄 What-If Simulation"
            onPress={() => {
              try { navigation.navigate('WhatIf', { scanId: scan.scanId }); } catch (_) {
                Alert.alert('What-If', 'Open this from the Home tab to run simulations.');
              }
            }}
            variant="outline"
            fullWidth
            style={styles.actionBtn}
          />
        </View>
      </Animated.View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    paddingBottom: 100,
  },
  error: {
    ...Typography.h3,
    color: Colors.danger,
    textAlign: 'center',
    marginTop: 100,
  },
  // Lab badge
  labBadge: {
    backgroundColor: `${Colors.success}15`,
    borderWidth: 1,
    borderColor: `${Colors.success}30`,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.round,
    alignItems: 'center',
  },
  labBadgeText: {
    ...Typography.caption,
    color: Colors.success,
    fontWeight: '600',
  },
  // Score section
  scoreSection: {
    alignItems: 'center',
    paddingVertical: Spacing.xxxl,
  },
  scoreInterpretation: {
    ...Typography.label,
    color: Colors.textSecondary,
    marginTop: Spacing.lg,
  },
  // Section
  sectionTitle: {
    ...Typography.h3,
    color: Colors.textPrimary,
    paddingHorizontal: Spacing.lg,
    marginTop: Spacing.xl,
    marginBottom: Spacing.md,
  },
  // Disease scroll
  diseaseScroll: {
    paddingHorizontal: Spacing.md,
    gap: 0,
  },
  // Vitals scroll
  vitalsScroll: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  // ARE
  areCard: {
    marginHorizontal: Spacing.lg,
  },
  areSummary: {
    ...Typography.bodyLarge,
    color: Colors.textPrimary,
    marginBottom: Spacing.md,
    lineHeight: 24,
  },
  areDetail: {
    ...Typography.body,
    color: Colors.textSecondary,
    marginBottom: Spacing.sm,
    lineHeight: 22,
    paddingLeft: Spacing.sm,
  },
  featureSection: {
    marginTop: Spacing.lg,
  },
  featureTitle: {
    ...Typography.label,
    color: Colors.textPrimary,
    marginBottom: Spacing.md,
  },
  featureRow: {
    marginBottom: Spacing.sm,
  },
  featureBar: {
    height: 6,
    backgroundColor: Colors.surfaceBorder,
    borderRadius: 3,
    marginBottom: 4,
  },
  featureBarFill: {
    height: 6,
    backgroundColor: Colors.primary,
    borderRadius: 3,
  },
  featureLabel: {
    ...Typography.caption,
    color: Colors.textTertiary,
  },
  counterfactualCard: {
    marginTop: Spacing.lg,
    backgroundColor: 'rgba(0, 212, 170, 0.05)',
    borderColor: 'rgba(0, 212, 170, 0.15)',
  },
  counterfactualTitle: {
    ...Typography.label,
    color: Colors.secondary,
    marginBottom: Spacing.xs,
  },
  counterfactualText: {
    ...Typography.body,
    color: Colors.textSecondary,
    lineHeight: 22,
  },
  // Actions
  actions: {
    paddingHorizontal: Spacing.lg,
    marginTop: Spacing.xxxl,
    gap: Spacing.md,
  },
  actionBtn: {
    borderRadius: BorderRadius.md,
  },
  // Thermal data
  thermalCard: {
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
  },
  thermalTitle: {
    ...Typography.h4,
    color: Colors.textPrimary,
    marginBottom: Spacing.md,
  },
  thermalStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: Spacing.md,
  },
  thermalStat: {
    alignItems: 'center',
  },
  thermalStatValue: {
    ...Typography.h3,
    color: Colors.hypertension,
  },
  thermalStatLabel: {
    ...Typography.caption,
    color: Colors.textTertiary,
    marginTop: 2,
  },
  thermalInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.xs,
    gap: Spacing.sm,
  },
  thermalInfoLabel: {
    ...Typography.caption,
    color: Colors.textSecondary,
    width: 80,
  },
  thermalInfoValue: {
    ...Typography.caption,
    color: Colors.textPrimary,
    fontWeight: '700',
  },
  thermalWarmthBar: {
    flex: 1,
    height: 6,
    backgroundColor: Colors.surfaceBorder,
    borderRadius: 3,
    overflow: 'hidden',
  },
  thermalWarmthFill: {
    height: '100%',
    borderRadius: 3,
  },
  thermalZoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Spacing.xs,
    gap: Spacing.sm,
  },
  thermalZoneDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  thermalZoneName: {
    ...Typography.caption,
    color: Colors.textSecondary,
    flex: 1,
  },
  thermalZoneTemp: {
    ...Typography.caption,
    color: Colors.textPrimary,
    fontWeight: '600',
  },
  // XAI Sections
  xaiCard: {
    marginHorizontal: Spacing.lg,
  },
  weightRow: {
    marginBottom: 14,
  },
  weightLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  weightLabel: {
    ...Typography.bodySmall,
    color: Colors.textSecondary,
  },
  weightPercent: {
    ...Typography.label,
    fontWeight: '700',
  },
  weightTrack: {
    height: 8,
    backgroundColor: Colors.surfaceContainerLow || '#f3f4f5',
    borderRadius: 4,
    overflow: 'hidden',
  },
  weightFill: {
    height: 8,
    borderRadius: 4,
  },
  reasoningText: {
    ...Typography.body,
    color: Colors.textSecondary,
    lineHeight: 24,
  },
  transRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  transLabel: {
    ...Typography.label,
    color: Colors.textTertiary,
    width: 90,
    fontWeight: '600',
  },
  transValue: {
    ...Typography.bodySmall,
    color: Colors.textSecondary,
    flex: 1,
  },
  transDisclaimer: {
    ...Typography.caption,
    color: Colors.danger,
    marginTop: 12,
    fontStyle: 'italic',
    textAlign: 'center',
  },
});
