/**
 * ArogyaNetra AI - Results Screen
 * Comprehensive scan results dashboard with health score, disease cards, vitals,
 * ARE explanations, diet recommendations, and downloadable reports
 */

import React, { useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Animated,
  Share,
  Alert,
} from 'react-native';
import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { GlassCard, AnimatedButton, RiskGauge, VitalPill } from '../components/common';
import { DiseaseCard } from '../components/results/DiseaseCard';
import { Colors, Typography, Spacing, BorderRadius } from '../theme';
import { useAppStore } from '../store/useAppStore';
import type { HomeStackParamList } from '../models/types';

type NavProp = NativeStackNavigationProp<HomeStackParamList, 'Results'>;
type RoutePropType = RouteProp<HomeStackParamList, 'Results'>;

export const ResultsScreen: React.FC = () => {
  const navigation = useNavigation<NavProp>();
  const route = useRoute<RoutePropType>();
  const { getStoredScan, currentScan, user } = useAppStore();

  const scan = getStoredScan(route.params.scanId) || currentScan;
  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 600,
      useNativeDriver: true,
    }).start();
  }, []);

  if (!scan) {
    return (
      <View style={styles.container}>
        <Text style={styles.error}>Scan not found</Text>
      </View>
    );
  }

  const { diseases, vitals, areExplanation, overallHealthScore } = scan;
  const scoreColor = overallHealthScore >= 70 ? Colors.success
    : overallHealthScore >= 50 ? Colors.warning
    : Colors.danger;

  const handleShareReport = async () => {
    try {
      const date = new Date(scan.timestamp).toLocaleDateString('en-IN', {
        day: 'numeric', month: 'long', year: 'numeric',
      });

      const report = `
🏥 AAROGYANETRA AI - Health Report
📅 ${date} | 📊 Score: ${overallHealthScore}/100

━━ VITALS ━━
❤️ HR: ${vitals.heartRate} BPM | SpO2: ${vitals.spo2Proxy}%
🩺 BP: ${vitals.bloodPressureSystolic}/${vitals.bloodPressureDiastolic} mmHg

━━ RISK ANALYSIS ━━
❤️ Hypertension: ${diseases.hypertension.category} (${Math.round(diseases.hypertension.riskScore * 100)}%)
🩸 Diabetes: ${diseases.diabetes.category} (${Math.round(diseases.diabetes.riskScore * 100)}%)
👁️ Anemia: ${diseases.anemia.category} (${Math.round(diseases.anemia.riskScore * 100)}%)

${areExplanation.summary}

💡 ${areExplanation.counterfactual}

⚠️ Screening tool only — not a diagnosis.
Generated by AarogyaNetra AI
`.trim();

      await Share.share({
        message: report,
        title: 'AarogyaNetra Health Report',
      });
    } catch (err) {
      Alert.alert('Error', 'Failed to share report.');
    }
  };

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      <Animated.View style={{ opacity: fadeAnim }}>
        {/* Lab Data Badge */}
        {scan.usedLabData && (
          <View style={styles.labBadge}>
            <Text style={styles.labBadgeText}>
              ✅ Lab report data used — Higher accuracy
            </Text>
          </View>
        )}

        {/* Health Score Header */}
        <View style={styles.scoreSection}>
          <RiskGauge
            score={overallHealthScore}
            size={160}
            strokeWidth={14}
            label="Health Score"
            color={scoreColor}
          />
          <Text style={styles.scoreInterpretation}>
            {overallHealthScore >= 80 ? '🌟 Excellent Health Profile' :
             overallHealthScore >= 65 ? '👍 Good — Minor attention needed' :
             overallHealthScore >= 45 ? '⚠️ Moderate — Consult a physician' :
             '🚨 Elevated Risk — Seek medical advice'}
          </Text>
        </View>

        {/* Disease Risk Cards */}
        <Text style={styles.sectionTitle}>Disease Analysis</Text>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.diseaseScroll}
        >
          <DiseaseCard
            name="Hypertension"
            riskLevel={diseases.hypertension.riskLevel}
            riskScore={diseases.hypertension.riskScore}
            confidence={diseases.hypertension.confidence}
            keyMetric={{
              label: 'BP',
              value: `${diseases.hypertension.systolicEstimate}/${diseases.hypertension.diastolicEstimate}`,
              unit: 'mmHg',
            }}
            category={diseases.hypertension.category}
            icon="❤️"
          />
          <DiseaseCard
            name="Diabetes"
            riskLevel={diseases.diabetes.riskLevel}
            riskScore={diseases.diabetes.riskScore}
            confidence={diseases.diabetes.confidence}
            keyMetric={{
              label: 'HbA1c',
              value: diseases.diabetes.hba1cProxy,
              unit: '%',
            }}
            category={diseases.diabetes.category}
            icon="🩸"
          />
          <DiseaseCard
            name="Anemia"
            riskLevel={diseases.anemia.riskLevel}
            riskScore={diseases.anemia.riskScore}
            confidence={diseases.anemia.confidence}
            keyMetric={{
              label: 'Hb',
              value: diseases.anemia.hemoglobinEstimate,
              unit: 'g/dL',
            }}
            category={diseases.anemia.category}
            icon="👁️"
          />
        </ScrollView>

        {/* Vitals Strip */}
        <Text style={styles.sectionTitle}>Vital Signs</Text>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.vitalsScroll}
        >
          <VitalPill
            label="Heart Rate"
            value={vitals.heartRate}
            unit="BPM"
            color={Colors.hypertension}
          />
          <VitalPill
            label="SpO2"
            value={vitals.spo2Proxy}
            unit="%"
            color={Colors.secondary}
          />
          <VitalPill
            label="Resp Rate"
            value={vitals.respiratoryRate}
            unit="/min"
            color={Colors.primary}
          />
          <VitalPill
            label="Systolic"
            value={vitals.bloodPressureSystolic}
            unit="mmHg"
            color={Colors.accent}
          />
          <VitalPill
            label="Diastolic"
            value={vitals.bloodPressureDiastolic}
            unit="mmHg"
            color={Colors.anemia}
          />
        </ScrollView>

        {/* ARE Explanation */}
        <Text style={styles.sectionTitle}>🧠 AI Explanation</Text>
        <GlassCard variant="accent" style={styles.areCard}>
          <Text style={styles.areSummary}>{areExplanation.summary}</Text>

          {areExplanation.details.map((detail, idx) => (
            <Text key={idx} style={styles.areDetail}>
              • {detail}
            </Text>
          ))}

          {/* Feature Importance */}
          {areExplanation.featureImportance.length > 0 && (
            <View style={styles.featureSection}>
              <Text style={styles.featureTitle}>Key Contributing Factors</Text>
              {areExplanation.featureImportance.map((f, idx) => (
                <View key={idx} style={styles.featureRow}>
                  <View style={styles.featureBar}>
                    <View
                      style={[
                        styles.featureBarFill,
                        { width: `${f.contribution * 100}%` },
                      ]}
                    />
                  </View>
                  <Text style={styles.featureLabel}>
                    {f.feature} ({Math.round(f.contribution * 100)}%)
                  </Text>
                </View>
              ))}
            </View>
          )}

          {/* Counterfactual */}
          <GlassCard style={styles.counterfactualCard}>
            <Text style={styles.counterfactualTitle}>💡 What could help?</Text>
            <Text style={styles.counterfactualText}>
              {areExplanation.counterfactual}
            </Text>
          </GlassCard>
        </GlassCard>

        {/* Action Buttons */}
        <View style={styles.actions}>
          <AnimatedButton
            title="🍽️ View Diet Recommendations"
            onPress={() => navigation.navigate('Diet', { scanId: scan.scanId })}
            variant="primary"
            fullWidth
            style={styles.actionBtn}
          />
          <AnimatedButton
            title="📤 Share / Download Report"
            onPress={handleShareReport}
            variant="primary"
            fullWidth
            style={{ ...styles.actionBtn, backgroundColor: Colors.secondary }}
          />
          <AnimatedButton
            title="📊 View DREM Trajectory"
            onPress={() => navigation.navigate('DREM', { scanId: scan.scanId })}
            variant="outline"
            fullWidth
            style={styles.actionBtn}
          />
          <AnimatedButton
            title="🔄 What-If Simulation"
            onPress={() => navigation.navigate('WhatIf', { scanId: scan.scanId })}
            variant="outline"
            fullWidth
            style={styles.actionBtn}
          />
          <AnimatedButton
            title="🔬 New Scan"
            onPress={() => navigation.navigate('Scanner')}
            variant="ghost"
            fullWidth
          />
        </View>
      </Animated.View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    paddingBottom: 100,
  },
  error: {
    ...Typography.h3,
    color: Colors.danger,
    textAlign: 'center',
    marginTop: 100,
  },
  // Lab badge
  labBadge: {
    backgroundColor: `${Colors.success}15`,
    borderWidth: 1,
    borderColor: `${Colors.success}30`,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.round,
    alignItems: 'center',
  },
  labBadgeText: {
    ...Typography.caption,
    color: Colors.success,
    fontWeight: '600',
  },
  // Score section
  scoreSection: {
    alignItems: 'center',
    paddingVertical: Spacing.xxxl,
  },
  scoreInterpretation: {
    ...Typography.label,
    color: Colors.textSecondary,
    marginTop: Spacing.lg,
  },
  // Section
  sectionTitle: {
    ...Typography.h3,
    color: Colors.textPrimary,
    paddingHorizontal: Spacing.lg,
    marginTop: Spacing.xl,
    marginBottom: Spacing.md,
  },
  // Disease scroll
  diseaseScroll: {
    paddingHorizontal: Spacing.md,
    gap: 0,
  },
  // Vitals scroll
  vitalsScroll: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  // ARE
  areCard: {
    marginHorizontal: Spacing.lg,
  },
  areSummary: {
    ...Typography.bodyLarge,
    color: Colors.textPrimary,
    marginBottom: Spacing.md,
    lineHeight: 24,
  },
  areDetail: {
    ...Typography.body,
    color: Colors.textSecondary,
    marginBottom: Spacing.sm,
    lineHeight: 22,
    paddingLeft: Spacing.sm,
  },
  featureSection: {
    marginTop: Spacing.lg,
  },
  featureTitle: {
    ...Typography.label,
    color: Colors.textPrimary,
    marginBottom: Spacing.md,
  },
  featureRow: {
    marginBottom: Spacing.sm,
  },
  featureBar: {
    height: 6,
    backgroundColor: Colors.surfaceBorder,
    borderRadius: 3,
    marginBottom: 4,
  },
  featureBarFill: {
    height: 6,
    backgroundColor: Colors.primary,
    borderRadius: 3,
  },
  featureLabel: {
    ...Typography.caption,
    color: Colors.textTertiary,
  },
  counterfactualCard: {
    marginTop: Spacing.lg,
    backgroundColor: 'rgba(0, 212, 170, 0.05)',
    borderColor: 'rgba(0, 212, 170, 0.15)',
  },
  counterfactualTitle: {
    ...Typography.label,
    color: Colors.secondary,
    marginBottom: Spacing.xs,
  },
  counterfactualText: {
    ...Typography.body,
    color: Colors.textSecondary,
    lineHeight: 22,
  },
  // Actions
  actions: {
    paddingHorizontal: Spacing.lg,
    marginTop: Spacing.xxxl,
    gap: Spacing.md,
  },
  actionBtn: {
    borderRadius: BorderRadius.md,
  },
});
